steps:
  # Build the docker images:
  - name: 'gcr.io/cloud-builders/docker'
    id: "Building Docker Image"
    args: ['build','-t','us-central1-docker.pkg.dev/sublime-state-413617/bank-churn-vertex-ai/bank_churn:$COMMIT_SHA','.']

  # Run Test cases



  # Push the docker image to artifact

  - name: 'gcr.io/cloud-builders/docker'
    id: "Pushing Docker File"
    args: ['push','us-central1-docker.pkg.dev/sublime-state-413617/bank-churn-vertex-ai/bank_churn:$COMMIT_SHA']

  # Deploy Cloud Run Service

  - name: 'gcr.io/cloud-builders/gcloud'
    id: "Deploying to cloud Run"
    args:
      - 'run'
      - 'deploy'
      - 'bank-churn-vertex-ai'
      - '--image'
      - 'us-central1-docker.pkg.dev/sublime-state-413617/bank-churn-vertex-ai/bank_churn:$COMMIT_SHA'
      - '--region'
      - 'us-central1'

options:
    logging: CLOUD_LOGGING_ONLY
